hmrc/individuals-income-received-api

- app/v1/controllers/requestParsers/validators/AmendFinancialDetailsValidator.scala
- app/v1/controllers/requestParsers/validators/RetrieveFinancialDetailsValidator.scala
> code fixes

- app/v1/controllers/requestParsers/validators/CreateAmendOtherCgtValidator.scala
- app/v1/controllers/requestParsers/validators/validations/ValueFormatErrorMessages.scala
- app/v1/models/request/createAmendOtherCgt/NonStandardGains.scala
- it/v1/endpoints/AmendDividendsControllerISpec.scala
- it/v1/endpoints/AmendFinancialDetailsControllerISpec.scala
- it/v1/endpoints/AmendForeignControllerISpec.scala
- it/v1/endpoints/AmendInsurancePoliciesControllerISpec.scala
- it/v1/endpoints/AmendOtherControllerISpec.scala
- it/v1/endpoints/AmendOtherEmploymentControllerISpec.scala
- it/v1/endpoints/AmendPensionsControllerISpec.scala
- it/v1/endpoints/AmendSavingsControllerISpec.scala
- resources/public/api/conf/1.0/docs/errors.md
- test/v1/controllers/requestParsers/validators/AmendOtherEmploymentValidatorSpec.scala
- test/v1/controllers/requestParsers/validators/AmendOtherValidatorSpec.scala
- test/v1/controllers/requestParsers/validators/AmendPensionsValidatorSpec.scala
- test/v1/controllers/requestParsers/validators/CreateAmendCgtPpdOverridesValidatorSpec.scala
- test/v1/controllers/requestParsers/validators/CreateAmendOtherCgtValidatorSpec.scala
> [MTDSA-9337] - Update CreateAndAmnedCgtOther validations

- app/v1/controllers/requestParsers/CreateAmendNonPayeEmploymentIncomeRequestParser.scala
- app/v1/controllers/requestParsers/validators/CreateAmendNonPayeEmploymentIncomeValidator.scala
- app/v1/controllers/requestParsers/validators/validations/DecimalValueValidation.scala
- app/v1/controllers/requestParsers/validators/validations/TipsValidation.scala
- app/v1/controllers/requestParsers/validators/validations/package.scala
- app/v1/models/errors/mtdErrors.scala
- test/v1/controllers/requestParsers/CreateAmendNonPayeEmploymentIncomeRequestParserSpec.scala
- test/v1/controllers/requestParsers/validators/CreateAmendNonPayeEmploymentIncomeValidatorSpec.scala
- test/v1/controllers/requestParsers/validators/validations/TipsValidationSpec.scala
- test/v1/mocks/validators/MockCreateAmendNonPayeEmploymentIncomeValidator.scala
- [MTDSA-9450] Create Amend Non Paye Employment Income models
- [MTDSA-9451] Create Amend Non Paye Employment Income parser & validator
> [MTDSA-9451] Create Amend Non Paye Employment Income parser & validator

- app/v1r6/connectors/IgnoreEmploymentConnector.scala
- app/v1r6/controllers/requestParsers/validators/validations/EmploymentIdValidation.scala
- app/v1r6/services/IgnoreEmploymentService.scala
- it/support/IntegrationBaseSpec.scala
- it/v1/endpoints/IgnoreEmploymentControllerISpec.scala
- it/v1r6/endpoints/IgnoreEmploymentControllerISpec.scala
- test/v1r6/connectors/IgnoreEmploymentConnectorSpec.scala
- test/v1r6/controllers/requestParsers/validators/validations/EmploymentIdValidationSpec.scala
- test/v1r6/services/IgnoreEmploymentServiceSpec.scala
- Update/add error codes
- Update employmentId regex
- Migrate to IFS
> MTDSA-9672

- .gitignore
- .sbtopts
- README.md
Reverts hmrc/individuals-income-received-api#337
> Revert "Add .sbtopts" and add memory comment to README

- app/v1/connectors/CreateAmendUkSavingsAnnualSummaryConnector.scala
- app/v1/models/request/createAmendUkSavingsAnnualSummary/CreateAmendUkSavingsAnnualSummary.scala
- app/v1/services/CreateAmendUkSavingsAnnualSummaryService.scala
- test/v1/connectors/CreateAmendUkSavingsAnnualSummaryConnectorSpec.scala
- test/v1/mocks/connectors/MockCreateAmendUkSavingsAnnualSummaryConnector.scala
- test/v1/services/CreateAmendUkSavingsAnnualSummaryServiceSpec.scala
Connector and service and tests for create amend uk savings account income
> Connector and service + tests

- app/v1/controllers/CreateAmendUkSavingsAnnualSummaryController.scala
- test/v1/controllers/CreateAmendUkSavingsAnnualSummaryControllerSpec.scala
Added auditing to the CreateAmendUKSavingsAnnualSummaryController
> Added auditing to CreateAmendUkSavingsAnnualSummaryController

- resources/public/api/conf/1.0/endpoints/ukSavingsAccount/amend.raml
- resources/public/api/conf/1.0/examples/ukSavingsAccount/uk_savings_account_amend_response.json
- resources/public/api/conf/1.0/examples/ukSavingsAccount/uk_savings_account_delete_request.json
- resources/public/api/conf/1.0/examples/ukSavingsAccount/uk_savings_account_retrieve_response.json
- resources/public/api/conf/1.0/schemas/uk_savings_account_amend_response.json
- resources/public/api/conf/1.0/schemas/uk_savings_account_retrieve_response.json
Updated RAML to allow for the 'DELETE' scenario on  Create and Amend a UK Annual Savings Summary
> Updated RAML to accommodate 'delete' scenario

- app/v1/connectors/DeleteOtherEmploymentIncomeConnector.scala
- app/v1/controllers/DeleteOtherEmploymentController.scala
- app/v1/models/request/deleteOtherEmploymentIncome/DeleteOtherEmploymentIncomeRequest.scala
- app/v1/models/request/deleteOtherEmploymentIncome/DeleteOtherEmploymentIncomeRequestRawData.scala
- app/v1/requestParsers/DeleteOtherEmploymentIncomeRequestParser.scala
- app/v1/requestParsers/validators/DeleteOtherEmploymentIncomeRequestValidator.scala
- app/v1/services/DeleteOtherEmploymentIncomeService.scala
- it/v1/endpoints/DeleteOtherEmploymentControllerISpec.scala
- test/v1/connectors/DeleteOtherEmploymentIncomeConnectorSpec.scala
- test/v1/controllers/DeleteOtherEmploymentControllerSpec.scala
- test/v1/mocks/connectors/MockDeleteOtherEmploymentIncomeConnector.scala
- test/v1/mocks/requestParsers/MockDeleteOtherEmploymentIncomeRequestParser.scala
- test/v1/mocks/services/MockDeleteOtherEmploymentIncomeService.scala
- test/v1/mocks/validators/MockDeleteOtherEmploymentIncomeValidator.scala
- test/v1/requestParsers/DeleteOtherEmploymentIncomeRequestParserSpec.scala
- test/v1/requestParsers/validators/DeleteOtherEmploymentIncomeValidatorSpec.scala
- test/v1/services/DeleteOtherEmploymentIncomeServiceSpec.scala
Squashed commits. A copy of - https://github.com/hmrc/individuals-income-received-api/pull/442
> MTDSA-12901 sign commits

- app/v1/connectors/CreateAmendUkSavingsAnnualSummaryConnector.scala
- app/v1/controllers/CreateAmendUkSavingsAnnualSummaryController.scala
- app/v1/services/CreateAmendUkSavingsAnnualSummaryService.scala
- it/v1/endpoints/CreateAmendUkSavingsAnnualSummaryControllerISpec.scala
- test/v1/connectors/CreateAmendUkSavingsAnnualSummaryConnectorSpec.scala
- test/v1/services/CreateAmendUkSavingsAnnualSummaryServiceSpec.scala
Updated, added TYS specific code to the connector and service
> Create Amend UK Savings Account Annual Summary

- app/v1/connectors/CreateAmendCgtPpdOverridesConnector.scala
- app/v1/connectors/CreateAmendCgtResidentialPropertyDisposalsConnector.scala
- app/v1/connectors/CreateAmendNonPayeEmploymentConnector.scala
- app/v1/connectors/CreateAmendOtherCgtConnector.scala
- app/v1/controllers/CreateAmendCgtPpdOverridesController.scala
- app/v1/controllers/CreateAmendCgtResidentialPropertyDisposalsController.scala
- app/v1/controllers/CreateAmendNonPayeEmploymentController.scala
- app/v1/controllers/CreateAmendOtherCgtController.scala
- app/v1/services/CreateAmendCgtPpdOverridesService.scala
- app/v1/services/CreateAmendCgtResidentialPropertyDisposalsService.scala
- app/v1/services/CreateAmendNonPayeEmploymentService.scala
- app/v1/services/CreateAmendOtherCgtService.scala
- app/v1/services/CreateAmendUkSavingsAnnualSummaryService.scala
- it/support/IntegrationBaseSpec.scala
- it/v1/endpoints/CreateAmendOtherCgtControllerISpec.scala
- fix broken CreateAmendOtherCgtControllerISpec
- add missing @Singleton annotation on controllers (& services and connectors)
> Reset wiremock in IntegrationBaseSpec

- app/v1/connectors/AmendInsurancePoliciesConnector.scala
- app/v1/controllers/AmendInsurancePoliciesController.scala
- app/v1/models/request/amendInsurancePolicies/AmendInsurancePoliciesRequest.scala
- app/v1/requestParsers/AmendInsurancePoliciesRequestParser.scala
- app/v1/services/AmendInsurancePoliciesService.scala
- it/v1/endpoints/AmendInsurancePoliciesControllerISpec.scala
- test/v1/connectors/AmendInsurancePoliciesConnectorSpec.scala
- test/v1/controllers/AmendInsurancePoliciesControllerSpec.scala
- test/v1/requestParsers/AmendInsurancePoliciesRequestParserSpec.scala
- test/v1/services/AmendInsurancePoliciesServiceSpec.scala
Changes to add TYS endpoint to AmendInsurancePolicies
> MTDSA-14134: TYS changes for Create and Amend Insurance Policies Income

- app/v1/models/request/amendFinancialDetails/emploment/AmendEmployment.scala
- test/v1/connectors/AmendFinancialDetailsConnectorSpec.scala
- test/v1/controllers/AmendFinancialDetailsControllerSpec.scala
- test/v1/models/request/amendFinancialDetails/AmendFinancialDetailsRequestBodySpec.scala
- test/v1/models/request/amendFinancialDetails/employment/AmendEmploymentSpec.scala
- test/v1/requestParsers/AmendFinancialDetailsRequestParserSpec.scala
- test/v1/services/AmendFinancialDetailsServiceSpec.scala
MTDSA-14364 update models for offPayrollWorker
> MTDSA-14364 update models for offPayrollWorker

- resources/public/api/conf/1.0/endpoints/employments/financialDetails/retrieve.raml
MTDSA-14157 - update endpoint description in raml
> MTDSA-14157 - update endpoint description in raml

- app/api/models/errors/mtdErrors.scala
- app/v1/controllers/AmendFinancialDetailsController.scala
- app/v1/requestParsers/validators/AmendFinancialDetailsValidator.scala
- it/v1/endpoints/AmendFinancialDetailsControllerISpec.scala
- test/v1/requestParsers/validators/AmendFinancialDetailsValidatorSpec.scala
in [v9.8.1. API#1935(1643) - Amend Employment Financial Details - TY (23-24)](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=561971214)
> MTDSA-14539: Updated validation for OffPayrollWorker

- app/v1/models/request/amendSavings/AmendForeignInterestItem.scala
- app/v1/requestParsers/validators/CreateAmendSavingsValidator.scala
- resources/public/api/conf/1.0/schemas/savings_definitions.json
- test/v1/controllers/CreateAmendSavingsControllerSpec.scala
- test/v1/models/request/amendSavings/AmendForeignInterestItemSpec.scala
- test/v1/models/request/amendSavings/CreateCreateAmendSavingsRequestBodySpec.scala
- test/v1/requestParsers/CreateAmendSavingsRequestParserSpec.scala
- test/v1/requestParsers/CreateCreateAmendSavingsRequestParserSpec.scala
- test/v1/requestParsers/validators/CreateAmendSavingsValidatorSpec.scala
Changes to make foreignInterest[].foreignTaxCreditRelief optional.
> MTDSA-13817 bug fix create and amend savings foreignTaxCreditRelief

- app/v1/models/response/retrieveOther/AllOtherIncomeReceivedWhilstAbroadItem.scala
- test/v1/models/response/retrieveOther/RetrieveOtherResponseSpec.scala
- foreignTaxCreditRelief to be set to false if missing from response body
- Unit test added for bug fix
> MTDSA-13879 Completed bug fix 

- app/config/AppConfig.scala
- app/config/FeatureSwitches.scala
- app/v1/controllers/AmendFinancialDetailsController.scala
- app/v1/models/request/amendFinancialDetails/AmendFinancialDetailsRawData.scala
- app/v1/models/request/amendFinancialDetails/emploment/AmendEmployment.scala
- app/v1/requestParsers/AmendFinancialDetailsRequestParser.scala
- app/v1/requestParsers/validators/AmendFinancialDetailsValidator.scala
- conf/application.conf
- it/v1/endpoints/AmendFinancialDetailsControllerISpec.scala
- project/AppDependencies.scala
- test/config/FeatureSwitchesSpec.scala
- test/v1/connectors/AmendFinancialDetailsConnectorSpec.scala
- test/v1/controllers/AmendFinancialDetailsControllerSpec.scala
- test/v1/mocks/requestParsers/MockAmendFinancialDetailsRequestParser.scala
- test/v1/mocks/validators/MockAmendFinancialDetailsValidator.scala
- test/v1/models/request/amendFinancialDetails/AmendFinancialDetailsRequestBodySpec.scala
- test/v1/models/request/amendFinancialDetails/employment/AmendEmploymentSpec.scala
- test/v1/requestParsers/AmendFinancialDetailsRequestParserSpec.scala
- test/v1/requestParsers/validators/AmendFinancialDetailsValidatorSpec.scala
Added Feature switch for offPayrollWorker
Given that MTDSA-14880 was already done, included some minor tweaks here as required to test that the feature switch is working correctly.
NEW
Updated model (downstream does not accept offPayrollWorker = false - only true is allowed)
> MTDSA-14877: Added opw feature switch and updated model, parser and validator

- app/config/AppConfig.scala
- app/definition/ApiDefinitionFactory.scala
- conf/application.conf
- it/config/DocumentationControllerISpec.scala
- test/api/services/EnrolmentsAuthServiceSpec.scala
- test/definition/ApiDefinitionFactorySpec.scala
https://jira.tools.tax.service.gov.uk/browse/MTDSA-16008
> MTDSA-16008 make confidence level configurable

- resources/public/api/conf/1.0/common/pathParameters.yaml
- resources/public/api/conf/1.0/savings_uk_accounts_retrieve.yaml
https://jira.tools.tax.service.gov.uk/browse/MTDSA-16124
> MTDSA-16124 fix tax year in oas docs

- resources/public/api/conf/1.0/employments_other_retrieve.yaml
MTDSA-15361 - add yaml for new error
> MTDSA-15361 - add yaml for new GTS

- resources/public/api/conf/2.0/uk_dividends_delete.yaml
Update description for delete uk dividends income annual summary.
**_Scenario simulation using Gov-Test-Scenario headers is only available in the sandbox environment. In sandbox, this endpoint requires a DELETE request with a Gov-Test-Scenario header to simulate a success response._**
> MTDSA-18830 update description
